### ISSUE TITLE
SDL3 binding

### ISSUE THREAD

**Issue by erdemserhatergen** [HexaEngine/Hexa.NET.SDL#1]
Do you have any plans to make binding for sdl3 and sdl3 image?

I've been using some of your bindings and they are really amazing. Thanks for the hard work.

**Comment by JunaMeinhold** [comment]
Hi, i will add SDL3 as soon as the first stable release drops.

**Comment by JunaMeinhold** [comment]
@erdemserhatergen 
Update: I finished working on the wrapper for SDL3 and uploaded it now on nuget
![image](https://github.com/user-attachments/assets/2ea7d69f-a29b-43d1-9a45-b2b64336f230)
