### ISSUE TITLE
No SDL_BlitSurface in SDL2?

### ISSUE THREAD

**Issue by TJHeuvel** [HexaEngine/Hexa.NET.SDL#3]
Hiya, i'm looking for the [SDL_BlitSurface](https://wiki.libsdl.org/SDL2/SDL_BlitSurface) method, but there is none exposed in SDL2. Trying to follow this tutorial: https://lisyarus.github.io/blog/posts/implementing-a-tiny-cpu-rasterizer-part-1.html#section-creating-a-window

It appears from the SDL source using upperblit is the same? https://github.com/HexaEngine/Hexa.NET.SDL/blob/89001d9a224ff85fc913a2613841e7e10ebab3fb/Generator/sdl2/include/SDL_surface.h#L861

**Comment by JunaMeinhold** [comment]
Hi, the headers in this project are just copied from the official sdl repository, so yeah both are the same/it's an alias for the UpperBlit method.

**Comment by JunaMeinhold** [comment]
Okay done, i improved the generator to now be able to generate aliases for functions.
Uploaded the nuget package should be available any minute
![image](https://github.com/user-attachments/assets/34d6ab04-19ad-46f3-9717-eeaf981dd2e5)

**Comment by TJHeuvel** [comment]
Thats amazing, thanks!
